# Generated by Django 3.2.18 on 2023-10-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_client_plan'),
        ('wagtail_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user', to='customers.client'),
        ),
        migrations.CreateModel(
            name='SmtpAuthenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_user', models.CharField(max_length=50)),
                ('smtp_password', models.CharField(max_length=128)),
                ('smtp_host', models.CharField(max_length=100)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=False)),
                ('fail_silently', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('timeout', models.PositiveIntegerField(blank=True, null=True)),
                ('ssl_keyfile', models.FileField(blank=True, null=True, upload_to='')),
                ('ssl_certfile', models.FileField(blank=True, null=True, upload_to='')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_smtp_auth', to='customers.client')),
            ],
        ),
    ]
