# Generated by Django 3.2.18 on 2023-10-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtail_tenants', '0002_auto_20231022_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpauthenticator',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_auth', to='wagtailcore.site'),
        ),
    ]
