# Generated by Django 3.2.18 on 2023-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tenants', '0003_smtpauthenticator_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtpauthenticator',
            old_name='use_tls',
            new_name='use_tsl',
        ),
        migrations.AddField(
            model_name='smtpauthenticator',
            name='email',
            field=models.EmailField(default='foo@bar.de', max_length=254),
            preserve_default=False,
        ),
    ]
