# Generated by Django 3.2.18 on 2023-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_tenants', '0005_rename_use_tsl_smtpauthenticator_use_tls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpauthenticator',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Leave blank to use the same password as the email address.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='smtpauthenticator',
            name='smtp_user',
            field=models.CharField(blank=True, help_text='Leave blank to use the same username as the email address.', max_length=50, null=True),
        ),
    ]
