# Generated by Django 3.2.10 on 2021-12-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_clientbackup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientbackup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
