# Generated by Django 3.2.18 on 2023-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20230321_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeature',
            name='app_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientfeature',
            name='menu_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ClientFeatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('features', models.ManyToManyField(blank=True, to='customers.ClientFeature')),
            ],
        ),
    ]
