# Generated by Django 3.2.18 on 2023-10-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_client_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='customers.clientfeaturegroup'),
        ),
    ]
