# Generated by Django 3.2.18 on 2023-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_client_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='customers.ClientFeature'),
        ),
    ]
